### PR TITLE
Update analytics-for-microgateway.md

### PR DESCRIPTION
**Pull request by davidarputharaj19**
update task.UploadFiles into taskUploadFiles

### Issues

Fixes #

---
#### Maintainers: Check before merge
- [ ] Manual verification

### CODE REVIEW

**Review by Mariangela — APPROVED** [review]

**Comment by Mariangela** [comment]
@Rajith90 , can you please review this PR from a technical point of view.

**Comment by Mariangela** [comment]
@davidarputharaj19, please resolve the merge conflict

**Comment by HeshanSudarshana** [comment]
This change is added from https://github.com/wso2/docs-mg/commit/33b42f45dea4e8afd5b19c6dd1cc0c2c84b735f5

**Comment by Mariangela** [comment]
@davidarputharaj19, we closed this PR because this has already been fixed in another PR. Thank you so much for your contribution in terms of helping to keep the WSO2 API Microgateway documentation up-to-date.  We look forward to your continued support.

**Pull request closed without merging**
